/* Auto-generated by genmsg_cpp for file /home/akshay/ros_workspace/sensor_model_ardrone/msg/Feature_Keypoint.msg */
#ifndef SENSOR_MODEL_ARDRONE_MESSAGE_FEATURE_KEYPOINT_H
#define SENSOR_MODEL_ARDRONE_MESSAGE_FEATURE_KEYPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace sensor_model_ardrone
{
template <class ContainerAllocator>
struct Feature_Keypoint_ {
  typedef Feature_Keypoint_<ContainerAllocator> Type;

  Feature_Keypoint_()
  : header()
  , x(0.0)
  , y(0.0)
  , size(0.0)
  , angle(0.0)
  , response(0.0)
  , octave(0)
  , class_id(0)
  {
  }

  Feature_Keypoint_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , size(0.0)
  , angle(0.0)
  , response(0.0)
  , octave(0)
  , class_id(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _size_type;
  double size;

  typedef double _angle_type;
  double angle;

  typedef double _response_type;
  double response;

  typedef int32_t _octave_type;
  int32_t octave;

  typedef int32_t _class_id_type;
  int32_t class_id;


  typedef boost::shared_ptr< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Feature_Keypoint
typedef  ::sensor_model_ardrone::Feature_Keypoint_<std::allocator<void> > Feature_Keypoint;

typedef boost::shared_ptr< ::sensor_model_ardrone::Feature_Keypoint> Feature_KeypointPtr;
typedef boost::shared_ptr< ::sensor_model_ardrone::Feature_Keypoint const> Feature_KeypointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sensor_model_ardrone

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bcb04017389001996e75359fda65d637";
  }

  static const char* value(const  ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbcb0401738900199ULL;
  static const uint64_t static_value2 = 0x6e75359fda65d637ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_model_ardrone/Feature_Keypoint";
  }

  static const char* value(const  ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float64 x\n\
float64 y\n\
\n\
float64 size\n\
float64 angle\n\
float64 response\n\
int32 octave\n\
int32 class_id\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.size);
    stream.next(m.angle);
    stream.next(m.response);
    stream.next(m.octave);
    stream.next(m.class_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Feature_Keypoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sensor_model_ardrone::Feature_Keypoint_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "size: ";
    Printer<double>::stream(s, indent + "  ", v.size);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "response: ";
    Printer<double>::stream(s, indent + "  ", v.response);
    s << indent << "octave: ";
    Printer<int32_t>::stream(s, indent + "  ", v.octave);
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SENSOR_MODEL_ARDRONE_MESSAGE_FEATURE_KEYPOINT_H

